alias: WizMote Find MAC
description: "Sends notification with MAC, button number and event type whenever any button press on a WizMote is detected."
trigger:
  - platform: event
    event_type: esphome.wizmote_choose
  - platform: event
    event_type: esphome.wizmote_action
action:
  - service: notify.persistent_notification
    data:
      message: >-
        Button {{trigger.event.data.button}} ({{trigger.event.event_type}}) pressed on WizMote with MAC:
        {{trigger.event.data.mac}}
mode: single
