alias: WizMote Find MAC
description: ""
trigger:
  - platform: event
    event_type: esphome.wizmote_choose
  - platform: event
    event_type: esphome.wizmote_action
    event_data: {}
condition: []
action:
  - service: notify.persistent_notification
    metadata: {}
    data:
      message: >-
        Button {{trigger.event.data.button}} ({{trigger.event.event_type}}) pressed on WizMote with MAC:
        {{trigger.event.data.mac}}
mode: single
